import os
from typing import final

__version__: str
MAX_COLLABORATION_BYTES: int

class XlsxError(Exception): ...
class ParseError(XlsxError): ...
class RangeError(XlsxError): ...
class RenderError(XlsxError): ...
class InvalidUpdateError(XlsxError): ...
class CollaborativeStateError(XlsxError): ...
class StaleProposalError(XlsxError):
    cells: list[str]
class NotCollaborativeError(XlsxError): ...

@final
class CellError:
    @property
    def code(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Png:
    @property
    def bytes(self) -> bytes: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def write(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int: ...

@final
class Calculation:
    @property
    def changed(self) -> int: ...
    @property
    def cycles(self) -> int: ...
    @property
    def limited(self) -> int: ...

@final
class Mutation:
    @property
    def applied(self) -> bool: ...
    @property
    def changed(self) -> list[str]: ...
    @property
    def cycles(self) -> list[str]: ...
    @property
    def limited(self) -> list[str]: ...
    def __bool__(self) -> bool: ...

@final
class History:
    @property
    def can_undo(self) -> bool: ...
    @property
    def can_redo(self) -> bool: ...
    @property
    def undo_depth(self) -> int: ...
    @property
    def redo_depth(self) -> int: ...

@final
class ProposedEdit:
    @property
    def sheet(self) -> int: ...
    @property
    def address(self) -> str: ...
    @property
    def input(self) -> str: ...
    @property
    def before(self) -> str: ...
    @property
    def after(self) -> str: ...

@final
class Proposal:
    @property
    def id(self) -> str: ...
    @property
    def agent_id(self) -> str: ...
    @property
    def note(self) -> str | None: ...
    @property
    def edits(self) -> list[ProposedEdit]: ...

@final
class Workbook:
    @staticmethod
    def open(data: bytes) -> Workbook: ...
    @staticmethod
    def open_path(path: str | os.PathLike[str]) -> Workbook: ...
    @staticmethod
    def open_recalculated(data: bytes, *, now_serial: float | None = ...) -> Workbook: ...
    def recalculate(self, *, now_serial: float | None = ...) -> Calculation: ...
    @property
    def sheet_count(self) -> int: ...
    @property
    def sheet_names(self) -> list[str]: ...
    def sheet_index(self, sheet: int | str) -> int: ...
    def value(
        self, sheet: int | str, address: str
    ) -> bool | float | str | CellError | None: ...
    def formula(self, sheet: int | str, address: str) -> str | None: ...
    def set(
        self,
        sheet: int | str,
        address: str,
        value: str,
        *,
        now_serial: float | None = ...,
    ) -> Mutation: ...
    @staticmethod
    def open_collaborative(
        data: bytes,
        *,
        client_id: int | None = ...,
        recalculate: bool = ...,
        now_serial: float | None = ...,
    ) -> Workbook: ...
    @property
    def client_id(self) -> int: ...
    @property
    def is_collaborative(self) -> bool: ...
    def state_vector(self) -> bytes: ...
    def state_as_update(self) -> bytes: ...
    def diff(self, state_vector: bytes) -> bytes: ...
    def apply_update(
        self, update: bytes, *, now_serial: float | None = ...
    ) -> Mutation: ...
    @property
    def can_undo(self) -> bool: ...
    @property
    def can_redo(self) -> bool: ...
    def history(self) -> History: ...
    def undo(self, *, now_serial: float | None = ...) -> Mutation: ...
    def redo(self, *, now_serial: float | None = ...) -> Mutation: ...
    def set_many(
        self,
        sheet: int | str,
        edits: list[tuple[str, str]],
        *,
        now_serial: float | None = ...,
    ) -> Mutation: ...
    def propose(
        self,
        agent_id: str,
        edits: list[tuple[int | str, str, str]],
        *,
        note: str | None = ...,
        now_serial: float | None = ...,
    ) -> Proposal: ...
    def proposals(self) -> list[Proposal]: ...
    def accept_proposal(
        self, proposal_id: str, *, force: bool = ..., now_serial: float | None = ...
    ) -> Mutation: ...
    def reject_proposal(self, proposal_id: str) -> bool: ...
    @property
    def active_sheet(self) -> int:
        """The active tab stored in the workbook view."""
    def set_active_sheet(self, sheet: int | str) -> None:
        """Select and persist the workbook's active tab."""
    def merged_ranges(self, sheet: int | str, range: str) -> list[str]: ...
    def last_calculation(self) -> Calculation: ...
    def set_number_format(
        self, sheet: int | str, range: str, format: str, *, now_serial: float | None = ...
    ) -> Mutation: ...
    def set_style(
        self,
        sheet: int | str,
        range: str,
        *,
        bold: bool | None = ...,
        italic: bool | None = ...,
        strikethrough: bool | None = ...,
        font_family: str | None = ...,
        font_size: float | None = ...,
        text_color: str | None = ...,
        fill_color: str | None = ...,
        horizontal_alignment: str | None = ...,
        vertical_alignment: str | None = ...,
        text_wrapping: str | None = ...,
        now_serial: float | None = ...,
    ) -> Mutation: ...
    def render_png(
        self,
        sheet: int | str,
        *,
        scale: float = ...,
        range: str | None = ...,
        max_width: int | None = ...,
        max_height: int | None = ...,
    ) -> Png: ...
    def save(self) -> bytes: ...
    def save_path(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int: ...
