import os
from typing import final

__version__: str

class XlsxError(Exception): ...
class ParseError(XlsxError): ...
class RangeError(XlsxError): ...
class RenderError(XlsxError): ...

@final
class CellError:
    @property
    def code(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Png:
    @property
    def bytes(self) -> bytes: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def write(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int: ...

@final
class Calculation:
    @property
    def changed(self) -> int: ...
    @property
    def cycles(self) -> int: ...
    @property
    def limited(self) -> int: ...

@final
class Workbook:
    @staticmethod
    def open(data: bytes) -> Workbook: ...
    @staticmethod
    def open_path(path: str | os.PathLike[str]) -> Workbook: ...
    @staticmethod
    def open_recalculated(data: bytes, *, now_serial: float | None = ...) -> Workbook: ...
    def recalculate(self, *, now_serial: float | None = ...) -> Calculation: ...
    @property
    def sheet_count(self) -> int: ...
    @property
    def sheet_names(self) -> list[str]: ...
    def sheet_index(self, sheet: int | str) -> int: ...
    def value(
        self, sheet: int | str, address: str
    ) -> bool | float | str | CellError | None: ...
    def formula(self, sheet: int | str, address: str) -> str | None: ...
    def set(
        self,
        sheet: int | str,
        address: str,
        value: str,
        *,
        now_serial: float | None = ...,
    ) -> bool: ...
    def render_png(
        self,
        sheet: int | str,
        *,
        scale: float = ...,
        range: str | None = ...,
        max_width: int | None = ...,
        max_height: int | None = ...,
    ) -> Png: ...
    def save(self) -> bytes: ...
    def save_path(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int: ...
