/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Document {
  get author(): string
  set author(author: string)
  get origin(): string
  set origin(value: string)
  get timestamp(): string
  set timestamp(timestamp: string)
  get paragraphIds(): Promise<Array<string | null>>
  get warnings(): Promise<string[]>
  get templateVariables(): Promise<string[]>
  get text(): Promise<string>
  get structure(): Promise<DocumentStructure>
  body(): Promise<any>
  headers(): Promise<any>
  footers(): Promise<any>
  sections(): Promise<any>
  paragraphs(): Promise<any>
  tables(): Promise<any>
  paragraph(paragraphId: string): Promise<any | null>
  replaceParagraphText(paragraphId: string, text: string): Promise<EditReceipt>
  layout(input: any): Promise<LayoutResult>
  registerFont(face: FontFace): Promise<number>
  registerImage(image: ImageResource): Promise<void>
  renderPage(displayList: any, page?: number | undefined | null): Promise<RenderedPage>
  save(options?: SaveDocumentOptions | undefined | null): Promise<Buffer>
}
export type DocxDocument = Document

export interface DocumentStructure {
  bodyParagraphs: number
  bodyTables: number
  sections: number
  headers: number
  footers: number
  footnotes: number
  endnotes: number
}

export interface EditReceipt {
  paragraphId?: string
  story?: string
  start?: number
  end?: number
  newParagraphIds: Array<string>
  revisionIds: Array<string>
}

export interface FontFace {
  family: string
  data: Buffer
  bold?: boolean
  italic?: boolean
}

export interface ImageResource {
  relationshipId: string
  data: Buffer
  scope?: string
  part?: string
}

export interface LayoutResult {
  layout: any
  displayList: any
}

export declare function openDocument(data: Buffer, options?: OpenDocumentOptions | undefined | null): Promise<Document>

export interface OpenDocumentOptions {
  author?: string
  origin?: string
  timestamp?: string
}

export interface RenderedPage {
  data: Buffer
  skippedImages: number
}

export interface SaveDocumentOptions {
  timestamp?: string
  updateModifiedDate?: boolean
  modifiedBy?: string
}
