export { paintSlide, sizeCanvasForSlide } from './render/canvas';
export type { CanvasImageResolver, PaintSlideOptions, SlideCanvasLike } from './render/canvas';
export { CollaborationError, CollaborationProvider } from './collaboration';
export type {
  CollaborationUser,
  CollaborationErrorCode,
  CollaborationErrorListener,
  CollaborationProviderOptions,
  CollaborationReplica,
  CollaborationStatus,
  CollaborationStatusChange,
  CollaborationStatusListener,
  CollaborationTransport,
  CollaborationTransportEvent,
  CollaborationUpdateOrigin,
  PptxPresence,
  PptxPresenceCursor,
  PptxPresenceListener,
  PptxPresencePeer,
  PptxPresenceState,
  PptxPresenceUser,
} from './collaboration';
export { PRESENCE_LABEL_DURATION_MS, presenceColorForClientId } from './collaboration';
export {
  initWasm,
  inspectPresentation,
  isWasmAvailable,
  openPresentation,
  wasmVersion,
} from './wasm/loader';
export type {
  OpenPresentationOptions,
  PresentationHandle,
  WasmInitInput,
} from './wasm/loader';
export type {
  CaretStop,
  ColorValue,
  DeckSnapshot,
  GeometryPathCommand,
  HistoryResult,
  HitTestResult,
  ImagePrimitive,
  Paint,
  ParagraphSnapshot,
  PlaceholderPrimitive,
  PositionedGlyph,
  PositionedTextLine,
  PositionedTextRun,
  PresetShapeDraft,
  PptxFontFace,
  PrimitiveTransform,
  ShapeAdjustReceipt,
  ShapeDraft,
  ShapeFill,
  ShapeFillReceipt,
  ShapeKind,
  ShapeOutline,
  ShapePrimitive,
  ShapeReceipt,
  ShapeRect,
  ShapeSnapshot,
  ShapeStroke,
  ShapeStrokeReceipt,
  SlideDisplayList,
  SlidePrimitive,
  SlideReceipt,
  SlideSnapshot,
  StorySnapshot,
  Stroke,
  TextBoxPrimitive,
  TextReceipt,
  TextRunSnapshot,
  TextStyle,
  TextStylePatch,
  TextStyleSnapshot,
  TransformReceipt,
  UpdateEvent,
} from './types';
