export { paintSlide, sizeCanvasForSlide } from './render/canvas';
export { decodePresentationImage, needsElementDecode, presentationImageBlob } from './render/image';
export { StaleProposalError } from './proposals';
export type { Proposal, ProposalAcceptance, ProposalChange, ProposalDiffSlide, ProposalEdit, ProposalPreview, ProposalTextChange } from './proposals';
export type { CanvasImageResolver, PaintSlideOptions, SlideCanvasLike } from './render/canvas';
export { slideToPng } from './render/png';
export type { SlideToPngOptions } from './render/png';
export { CollaborationError, CollaborationProvider } from './collaboration';
export type {
  CollaborationUser,
  CollaborationErrorCode,
  CollaborationErrorListener,
  CollaborationProviderOptions,
  CollaborationReplica,
  CollaborationStatus,
  CollaborationStatusChange,
  CollaborationStatusListener,
  CollaborationTransport,
  CollaborationTransportEvent,
  CollaborationUpdateOrigin,
  PptxPresence,
  PptxPresenceCursor,
  PptxPresenceListener,
  PptxPresencePeer,
  PptxPresenceState,
  PptxPresenceUser,
} from './collaboration';
export { PRESENCE_LABEL_DURATION_MS, presenceColorForClientId } from './collaboration';
export {
  exportPptxMarkdown,
  exportPptxStructured,
  initWasm,
  inspectPresentation,
  isWasmAvailable,
  isProposalsAvailable,
  openPresentation,
  renderPptxMarkdown,
  wasmVersion,
} from './wasm/loader';
export { PptxExportError } from './structuredExport';
export type {
  ExportCompletion,
  ExportDiagnostic,
  ExportSeverity,
  MarkdownAnchor,
  PptxAnchor,
  PptxAnchorScope,
  PptxExportComment,
  PptxExportDiagnostic,
  PptxExportDiagnosticCode,
  PptxExportFailure,
  PptxExportFailureCode,
  PptxExportList,
  PptxExportMark,
  PptxExportNotes,
  PptxExportObject,
  PptxExportObjectKind,
  PptxExportOptions,
  PptxExportParagraph,
  PptxExportRefusal,
  PptxExportResult,
  PptxExportRun,
  PptxExportShape,
  PptxExportShapeKind,
  PptxExportSlide,
  PptxExportStory,
  PptxExportTable,
  PptxExportTableCell,
  PptxMarkdownContent,
  PptxMarkdownOptions,
  PptxSourceProvenance,
  PptxStructuredContent,
  PptxTextSpan,
} from './structuredExport';
export type {
  OpenPresentationOptions,
  PresentationHandle,
  UndoCaptureMode,
  WasmInitInput,
} from './wasm/loader';
export type {
  EditSuccess,
  OperationFailure,
  OperationRefusal,
  PptxEditFailure,
  PptxEditFailureCode,
  PptxEditHistory,
  PptxEditPreview,
  PptxEditReceipt,
  PptxEditRefusal,
  PptxEditRequest,
  PptxEditResult,
  PptxEditSource,
  PptxEditStep,
  PptxEditTarget,
  PptxFindMatch,
  PptxFindRequest,
  PptxFindResult,
  PptxFindScope,
  PptxParagraphText,
  PptxReadRequest,
  PptxReadResult,
  PptxShapeTarget,
  PptxSlideTarget,
  PptxStoryTarget,
  PptxStoryText,
  PptxTextField,
  PptxTextGuard,
  PptxTextRange,
  PptxTextTarget,
  PptxValidationResult,
  ValidationSuccess,
} from './edits';
export type {
  BlipEffect,
  CaretStop,
  ColorValue,
  CommentFlavor,
  CommentReceipt,
  CommentSnapshot,
  DeckSnapshot,
  EditProfile,
  GeometryPathCommand,
  HistoryProfile,
  HistoryResult,
  HitTestResult,
  ImageEffect,
  ImageCrop,
  ImagePrimitive,
  InheritedGeometry,
  LayoutProfile,
  Paint,
  ParagraphAlignment,
  ParagraphSnapshot,
  PictureDraft,
  PlaceholderPrimitive,
  PositionedGlyph,
  PositionedTextLine,
  PositionedTextRun,
  PresetShapeDraft,
  Profiled,
  ProfiledLayout,
  PptxFontFace,
  PptxTextMatch,
  PptxTextSearchOptions,
  PrimitiveTransform,
  ShapeAdjustReceipt,
  ShapeDraft,
  ShapeFill,
  ShapeFillReceipt,
  ShapeGradient,
  ShapeKind,
  ShapeLineEnd,
  ShapeOutline,
  ShapePrimitive,
  ShapeReceipt,
  ShapeRect,
  ShapeSnapshot,
  ShapeStroke,
  ShapeStrokeReceipt,
  ShapeZOrderReceipt,
  SlideDisplayList,
  SlidePrimitive,
  SlideReceipt,
  SlideSnapshot,
  StorySnapshot,
  Stroke,
  StrokeEnd,
  TextBoxPrimitive,
  TextReceipt,
  TextRunSnapshot,
  TextStyle,
  TextStylePatch,
  TextStyleSnapshot,
  TransformReceipt,
  UpdateEvent,
} from './types';
