import os
from typing import Any, final

__version__: str
MAX_COLLABORATION_BYTES: int

class PptxError(Exception): ...
class ParseError(PptxError): ...
class RangeError(PptxError): ...
class RenderError(PptxError): ...
class InvalidUpdateError(PptxError): ...
class CollaborativeStateError(PptxError): ...
class NotCollaborativeError(PptxError): ...
class UnsupportedWriteError(PptxError): ...

@final
class Rect:
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

@final
class Stroke:
    @property
    def color(self) -> str | None: ...
    @property
    def width_pt(self) -> float | None: ...

@final
class TextRun:
    @property
    def text(self) -> str: ...
    @property
    def bold(self) -> bool | None: ...
    @property
    def italic(self) -> bool | None: ...
    @property
    def font_size(self) -> float | None: ...
    @property
    def color(self) -> str | None: ...
    @property
    def font_family(self) -> str | None: ...
    @property
    def underline(self) -> str | None: ...

@final
class Paragraph:
    @property
    def id(self) -> str: ...
    @property
    def alignment(self) -> str | None: ...
    @property
    def level(self) -> int: ...
    @property
    def runs(self) -> list[TextRun]: ...
    @property
    def text(self) -> str: ...

@final
class Story:
    @property
    def id(self) -> str: ...
    @property
    def length(self) -> int:
        """Story length in UTF-16 code units, pilcrows included."""
    @property
    def paragraphs(self) -> list[Paragraph]: ...
    @property
    def text(self) -> str: ...

@final
class Shape:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str:
        """One of shape, picture, graphicFrame, or group."""
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rotation(self) -> float: ...
    @property
    def flip_h(self) -> bool: ...
    @property
    def flip_v(self) -> bool: ...
    @property
    def geometry(self) -> str: ...
    @property
    def adjustments(self) -> dict[str, float]: ...
    @property
    def fill_color(self) -> str | None: ...
    @property
    def outline_color(self) -> str | None: ...
    @property
    def placeholder(self) -> str | None: ...
    @property
    def media_path(self) -> str | None: ...
    @property
    def stories(self) -> list[Story]: ...
    @property
    def children(self) -> list[Shape]: ...
    @property
    def text(self) -> str: ...

@final
class Slide:
    @property
    def id(self) -> str: ...
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def layout(self) -> str | None: ...
    @property
    def part_path(self) -> str | None: ...
    @property
    def shapes(self) -> list[Shape]: ...
    @property
    def text(self) -> str: ...
    def __len__(self) -> int: ...

@final
class Deck:
    @property
    def width_emu(self) -> int: ...
    @property
    def height_emu(self) -> int: ...
    @property
    def slides(self) -> list[Slide]: ...
    def __len__(self) -> int: ...

@final
class Media:
    @property
    def path(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    @property
    def bytes(self) -> bytes: ...
    def write(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int: ...

@final
class DisplayList:
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def contract_version(self) -> int: ...
    @property
    def json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def write(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int:
        """Primitive count."""

@final
class SlideEdit:
    @property
    def slide_id(self) -> str: ...
    @property
    def from_index(self) -> int | None: ...
    @property
    def to_index(self) -> int | None: ...

@final
class ShapeEdit:
    @property
    def slide_id(self) -> str: ...
    @property
    def shape_id(self) -> str: ...
    @property
    def index(self) -> int: ...

@final
class TransformEdit:
    @property
    def slide_id(self) -> str: ...
    @property
    def shape_id(self) -> str: ...
    @property
    def before(self) -> Rect: ...
    @property
    def after(self) -> Rect: ...

@final
class FillEdit:
    @property
    def slide_id(self) -> str: ...
    @property
    def shape_id(self) -> str: ...
    @property
    def before(self) -> str | None: ...
    @property
    def after(self) -> str | None: ...

@final
class StrokeEdit:
    @property
    def slide_id(self) -> str: ...
    @property
    def shape_id(self) -> str: ...
    @property
    def before(self) -> Stroke | None: ...
    @property
    def after(self) -> Stroke | None: ...

@final
class AdjustEdit:
    @property
    def slide_id(self) -> str: ...
    @property
    def shape_id(self) -> str: ...
    @property
    def before(self) -> dict[str, float]: ...
    @property
    def after(self) -> dict[str, float]: ...

@final
class TextEdit:
    @property
    def story_id(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def text(self) -> str: ...
    def __len__(self) -> int: ...

@final
class Presentation:
    @staticmethod
    def open(data: bytes, *, limits: dict[str, int] | None = ...) -> Presentation: ...
    @staticmethod
    def open_path(
        path: str | os.PathLike[str], *, limits: dict[str, int] | None = ...
    ) -> Presentation: ...
    @staticmethod
    def open_collaborative(
        data: bytes,
        *,
        client_id: int | None = ...,
        limits: dict[str, int] | None = ...,
    ) -> Presentation: ...
    @property
    def client_id(self) -> int: ...
    @property
    def is_collaborative(self) -> bool: ...
    @property
    def is_edited(self) -> bool: ...
    author: str
    origin: str
    @property
    def slide_count(self) -> int: ...
    @property
    def slide_ids(self) -> list[str]: ...
    @property
    def width_emu(self) -> int: ...
    @property
    def height_emu(self) -> int: ...
    @property
    def layouts(self) -> list[str]:
        """Layout part paths, as `insert_slide` expects them."""
    def snapshot(self) -> Deck: ...
    def slide(self, slide: int | str) -> Slide: ...
    def story(self, story_id: str) -> Story: ...
    def media(self) -> list[Media]: ...
    def insert_slide(self, index: int, *, layout: str | None = ...) -> SlideEdit: ...
    def delete_slide(self, slide: int | str) -> SlideEdit: ...
    def move_slide(self, slide: int | str, index: int) -> SlideEdit: ...
    def add_text_box(
        self,
        slide: int | str,
        *,
        x: int,
        y: int,
        width: int,
        height: int,
        text: str = ...,
        name: str | None = ...,
        bold: bool | None = ...,
        italic: bool | None = ...,
        font_size: float | None = ...,
        color: str | None = ...,
        font_family: str | None = ...,
        underline: str | None = ...,
    ) -> ShapeEdit: ...
    def add_shape(
        self,
        slide: int | str,
        geometry: str,
        *,
        x: int,
        y: int,
        width: int,
        height: int,
        fill: str | None = ...,
        name: str | None = ...,
    ) -> ShapeEdit: ...
    def set_shape_fill(
        self, slide: int | str, shape_id: str, color: str | None
    ) -> FillEdit: ...
    def set_shape_stroke(
        self,
        slide: int | str,
        shape_id: str,
        *,
        color: str | None = ...,
        width_pt: float | None = ...,
    ) -> StrokeEdit: ...
    def set_shape_adjust(
        self, slide: int | str, shape_id: str, adjustments: dict[str, float]
    ) -> AdjustEdit: ...
    def remove_shape(self, slide: int | str, shape_id: str) -> ShapeEdit: ...
    def move_shape(
        self, slide: int | str, shape_id: str, x: int, y: int
    ) -> TransformEdit: ...
    def resize_shape(
        self, slide: int | str, shape_id: str, width: int, height: int
    ) -> TransformEdit: ...
    def insert_text(
        self,
        story_id: str,
        index: int,
        text: str,
        *,
        bold: bool | None = ...,
        italic: bool | None = ...,
        font_size: float | None = ...,
        color: str | None = ...,
        font_family: str | None = ...,
        underline: str | None = ...,
    ) -> TextEdit: ...
    def delete_text(self, story_id: str, start: int, end: int) -> TextEdit: ...
    def format_text(
        self,
        story_id: str,
        start: int,
        end: int,
        *,
        bold: bool | None = ...,
        italic: bool | None = ...,
        font_size: float | None = ...,
        color: str | None = ...,
        font_family: str | None = ...,
        underline: str | None = ...,
    ) -> TextEdit: ...
    def insert_paragraph_break(self, story_id: str, index: int) -> TextEdit: ...
    def register_font(
        self, family: str, data: bytes, *, bold: bool = ..., italic: bool = ...
    ) -> int: ...
    def render_slide(self, slide: int | str) -> DisplayList: ...
    def save(self) -> bytes:
        """Raises `UnsupportedWriteError` once the deck has been edited; the
        engine cannot write model edits back to PPTX yet."""
    def save_path(self, path: str | os.PathLike[str]) -> None:
        """Refuses once the deck has been edited."""
    def state_vector(self) -> bytes: ...
    def state_as_update(self) -> bytes: ...
    def diff(self, state_vector: bytes) -> bytes: ...
    def apply_update(self, update: bytes) -> Deck: ...
    @property
    def can_undo(self) -> bool: ...
    @property
    def can_redo(self) -> bool: ...
    def undo(self) -> bool: ...
    def redo(self) -> bool: ...
    def add_undo_barrier(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, slide: int | str) -> Slide: ...
