import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { validateComparison } from './results.mjs';

export const BEGIN = '<!-- BEGIN GENERATED VISUAL FIDELITY -->';
export const END = '<!-- END GENERATED VISUAL FIDELITY -->';
export const FORMATS = ['docx', 'pptx', 'xlsx'];

function score(samples, channel, revision) {
  const scores = [];
  for (const sample of samples) {
    const results = sample.comparisons.filter(
      (result) =>
        result.channel === channel &&
        (channel === 'published' ? result.version : result.renderer_source_commit) ===
          revision
    );
    if (results.length > 1) throw new Error('Duplicate sample/channel comparison');
    const result = results[0];
    if (!result) continue;
    if (result.status === 'failed') {
      if (
        !['capture', 'compare'].includes(result.stage) ||
        typeof result.error !== 'string' ||
        !result.error.trim() ||
        'penalized_ssim' in result
      )
        throw new Error('Invalid failed comparison');
    } else {
      if (result.status !== undefined && result.status !== 'ok')
        throw new Error('Invalid comparison status');
      validateComparison(result);
      scores.push(result);
    }
  }
  const paged = scores.filter(
    (result) =>
      Number.isInteger(result.reference_pages) && Number.isInteger(result.actual_pages)
  );
  return {
    count: scores.length,
    total: samples.length,
    value: scores.length
      ? (
          scores.reduce((sum, result) => sum + result.penalized_ssim, 0) / scores.length
        ).toFixed(4)
      : '—',
    exact: paged.filter((result) => result.reference_pages === result.actual_pages).length,
    paged: paged.length,
    pageError: paged.reduce(
      (sum, result) => sum + Math.abs(result.reference_pages - result.actual_pages),
      0
    ),
  };
}

export function renderSection(report) {
  if (!/^[a-f0-9]{40}$/.test(report.commit))
    throw new Error('Expected a full commit SHA');
  const short = report.commit.slice(0, 8);
  const commitLink = `[${short}](https://github.com/openooxml/betteroffice/commit/${report.commit})`;
  const measure = (format) => {
    const version = report.versions[format];
    if (!/^\d+\.\d+\.\d+(?:[-+][\w.-]+)?$/.test(version))
      throw new Error(`Invalid ${format} version`);
    const samples = report.samples.filter((sample) => sample.format === format);
    return {
      version,
      versionLink: `[${version}](https://www.npmjs.com/package/@betteroffice/${format}/v/${version})`,
      published: score(samples, 'published', version),
      current: score(samples, 'commit', report.commit),
    };
  };
  const ssimTable = (format) => {
    const { versionLink, published, current } = measure(format);
    return `| Latest published version | SSIM | Scored/total | Latest commit | SSIM | Scored/total |
| --- | ---: | ---: | --- | ---: | ---: |
| ${versionLink} | ${published.value} | ${published.count}/${published.total} | ${commitLink} | ${current.value} | ${current.count}/${current.total} |`;
  };
  const docx = measure('docx');
  const pages = (side) => (side.paged ? `${side.exact}/${side.paged}` : '—');
  const pageError = (side) => (side.paged ? String(side.pageError) : '—');
  const docxTable = `| | Latest published ${docx.versionLink} | Latest commit ${commitLink} |
| --- | ---: | ---: |
| Exact page counts | ${pages(docx.published)} | ${pages(docx.current)} |
| Absolute page error | ${pageError(docx.published)} | ${pageError(docx.current)} |
| SSIM | ${docx.published.value} | ${docx.current.value} |
| Scored/total | ${docx.published.count}/${docx.published.total} | ${docx.current.count}/${docx.current.total} |`;
  return `${BEGIN}
## Benchmarks

### Fidelity

*Generated by the [Benchmarks action](.github/workflows/visual-fidelity.yml).*

#### DOCX

Page agreement is reported on its own because a document either paginates as Word does or it does not; SSIM cannot express that.

${docxTable}

#### PPTX

${ssimTable('pptx')}

#### XLSX

${ssimTable('xlsx')}

SSIM is the mean page-penalized grayscale score at 150 DPI, without resampling or alignment correction. DOCX uses recorded page bounds with at most a one-pixel edge adjustment. Missing or extra pages are penalized. Exact page counts are the documents whose rendered page count equals the reference; absolute page error sums the per-document difference. All formats use pinned CDN fonts. XLSX uses recorded print ranges and scale; its score measures range rendering, not automatic print pagination. Means cover successful comparisons only; failed or missing comparisons have no score. Compare coverage alongside SSIM because the channels may score different subsets.

${END}`;
}

export function updateReadme(readme, section) {
  if (!section.startsWith(BEGIN) || !section.endsWith(END))
    throw new Error('Invalid generated section');
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (begin < 0 !== end < 0 || (begin >= 0 && end < begin))
    throw new Error('Broken generated markers');
  const stripped =
    begin >= 0
      ? readme.slice(0, begin) + readme.slice(end + END.length)
      : readme.replace(/^## Visual fidelity\n[\s\S]*?(?=^## |$(?![\s\S]))/m, '');
  const position = stripped.indexOf('## Contributing\n');
  if (position < 0) throw new Error('README has no Contributing section');
  return `${stripped.slice(0, position).trimEnd()}\n\n${section}\n\n${stripped.slice(
    position
  )}`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const [reportPath, readmePath = 'README.md'] = process.argv.slice(2);
  if (!reportPath) throw new Error('usage: readme.mjs report.json [README.md]');
  const section = renderSection(JSON.parse(await readFile(reportPath, 'utf8')));
  await writeFile(readmePath, updateReadme(await readFile(readmePath, 'utf8'), section));
}
