import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { summarizeError, validateComparison } from './results.mjs';

export const BEGIN = '<!-- BEGIN GENERATED VISUAL FIDELITY -->';
export const END = '<!-- END GENERATED VISUAL FIDELITY -->';
export const FORMATS = ['docx', 'pptx', 'xlsx'];

function score(samples, channel, revision) {
  const scores = [];
  const failures = [];
  for (const sample of samples) {
    const results = sample.comparisons.filter(
      (result) =>
        result.channel === channel &&
        (channel === 'published' ? result.version : result.renderer_source_commit) ===
          revision
    );
    if (results.length > 1) throw new Error('Duplicate sample/channel comparison');
    const result = results[0];
    if (!result) {
      failures.push({
        sample: sample.id,
        channel,
        stage: 'missing',
        error: 'No result for this revision',
      });
    } else if (result.status === 'failed') {
      if (
        !['capture', 'compare'].includes(result.stage) ||
        typeof result.error !== 'string' ||
        !result.error.trim() ||
        'penalized_ssim' in result
      )
        throw new Error('Invalid failed comparison');
      failures.push({
        sample: sample.id,
        channel,
        stage: result.stage,
        error: summarizeError(result.error),
      });
    } else {
      if (result.status !== undefined && result.status !== 'ok')
        throw new Error('Invalid comparison status');
      validateComparison(result);
      scores.push(result);
    }
  }
  return {
    count: scores.length,
    total: samples.length,
    failures,
    value: scores.length
      ? (
          scores.reduce((sum, result) => sum + result.penalized_ssim, 0) / scores.length
        ).toFixed(4)
      : '—',
  };
}

export function renderSection(report) {
  if (!/^[a-f0-9]{40}$/.test(report.commit))
    throw new Error('Expected a full commit SHA');
  const failures = [];
  const rows = FORMATS.map((format) => {
    const version = report.versions[format];
    if (!/^\d+\.\d+\.\d+(?:[-+][\w.-]+)?$/.test(version))
      throw new Error(`Invalid ${format} version`);
    const samples = report.samples.filter((sample) => sample.format === format);
    const published = score(samples, 'published', version);
    const current = score(samples, 'commit', report.commit);
    failures.push(...published.failures, ...current.failures);
    return `| ${format.toUpperCase()} | [${version}](https://www.npmjs.com/package/@betteroffice/${format}/v/${version}) | ${
      published.value
    } | ${published.count}/${published.total} | [${report.commit.slice(
      0,
      8
    )}](https://github.com/openooxml/betteroffice/commit/${report.commit}) | ${
      current.value
    } | ${current.count}/${current.total} | ${published.failures.length} / ${
      current.failures.length
    } |`;
  });
  const cell = (value) =>
    String(value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/\|/g, '&#124;')
      .replace(/[\r\n]/g, ' ')
      .replace(/([\\`*_[\]])/g, '\\$1');
  const failureSection = failures.length
    ? `\nFailed or missing comparisons (excluded from SSIM):\n\n| Sample | Channel | Stage | Error |\n| --- | --- | --- | --- |\n${failures
        .map(
          (failure) =>
            `| ${cell(failure.sample)} | ${failure.channel} | ${failure.stage} | ${cell(
              failure.error
            )} |`
        )
        .join('\n')}\n`
    : '\nAll selected samples were scored in both channels.\n';
  return `${BEGIN}
## Visual fidelity

*Generated by the [Visual fidelity action](.github/workflows/visual-fidelity.yml).*

| Format | Latest published version | SSIM | Scored/total | Latest commit | SSIM | Scored/total | Failed or missing (published / commit) |
| --- | --- | ---: | ---: | --- | ---: | ---: | ---: |
${rows.join('\n')}

SSIM is the mean page-penalized grayscale score at 150 DPI, without resampling or alignment correction. DOCX uses recorded page bounds with at most a one-pixel edge adjustment. Missing or extra pages are penalized. All formats use pinned CDN fonts. XLSX uses recorded print ranges and scale; its score measures range rendering, not automatic print pagination. Means cover successful comparisons only; failed or missing comparisons have no score. Compare coverage alongside SSIM because the channels may score different subsets.
${failureSection}
${END}`;
}

export function updateReadme(readme, section) {
  if (!section.startsWith(BEGIN) || !section.endsWith(END))
    throw new Error('Invalid generated section');
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (begin < 0 !== end < 0 || (begin >= 0 && end < begin))
    throw new Error('Broken generated markers');
  const stripped =
    begin >= 0
      ? readme.slice(0, begin) + readme.slice(end + END.length)
      : readme.replace(/^## Visual fidelity\n[\s\S]*?(?=^## |$(?![\s\S]))/m, '');
  const position = stripped.indexOf('## Contributing\n');
  if (position < 0) throw new Error('README has no Contributing section');
  return `${stripped.slice(0, position).trimEnd()}\n\n${section}\n\n${stripped.slice(
    position
  )}`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const [reportPath, readmePath = 'README.md'] = process.argv.slice(2);
  if (!reportPath) throw new Error('usage: readme.mjs report.json [README.md]');
  const section = renderSection(JSON.parse(await readFile(reportPath, 'utf8')));
  await writeFile(readmePath, updateReadme(await readFile(readmePath, 'utf8'), section));
}
