import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

export const BEGIN = '<!-- BEGIN GENERATED VISUAL FIDELITY -->';
export const END = '<!-- END GENERATED VISUAL FIDELITY -->';
export const FORMATS = ['docx', 'pptx', 'xlsx'];

function score(samples, channel, revision) {
  const scores = samples.flatMap((sample) =>
    sample.comparisons.filter(
      (result) =>
        result.channel === channel &&
        (channel === 'published' ? result.version : result.renderer_source_commit) ===
          revision
    )
  );
  for (const result of scores) {
    if (
      !result.source_verified ||
      result.reference?.status !== 'ok' ||
      result.actual?.status !== 'ok' ||
      result.reference.sha256 !== result.actual.sha256 ||
      !Number.isFinite(result.penalized_ssim) ||
      Math.abs(result.penalized_ssim) > 1
    ) {
      throw new Error('Cannot publish an incomplete or mismatched comparison');
    }
  }
  return {
    count: scores.length,
    value: scores.length
      ? (
          scores.reduce((sum, result) => sum + result.penalized_ssim, 0) / scores.length
        ).toFixed(4)
      : '—',
  };
}

export function renderSection(report) {
  if (!/^[a-f0-9]{40}$/.test(report.commit))
    throw new Error('Expected a full commit SHA');
  const rows = FORMATS.map((format) => {
    const version = report.versions[format];
    if (!/^\d+\.\d+\.\d+(?:[-+][\w.-]+)?$/.test(version))
      throw new Error(`Invalid ${format} version`);
    const samples = report.samples.filter((sample) => sample.format === format);
    const published = score(samples, 'published', version);
    const current = score(samples, 'commit', report.commit);
    return `| ${format.toUpperCase()} | [${version}](https://www.npmjs.com/package/@betteroffice/${format}/v/${version}) | ${published.value} | [${report.commit.slice(0, 8)}](https://github.com/openooxml/betteroffice/commit/${report.commit}) | ${current.value} | ${published.count} / ${current.count} |`;
  });
  const sources = report.samples.map((sample) => {
    const url = new URL(sample.metadata_url);
    if (
      url.origin !== 'https://corpus.betteroffice.dev' ||
      !/^[a-z0-9-]+$/.test(sample.id)
    ) {
      throw new Error('Invalid public sample metadata URL');
    }
    return `[${sample.id}](${url.href})`;
  });
  return `${BEGIN}
## Visual fidelity

*Generated by the [Visual fidelity action](.github/workflows/visual-fidelity.yml).*

| Format | Latest published version | SSIM | Latest commit | SSIM | Samples (published / commit) |
| --- | --- | ---: | --- | ---: | ---: |
${rows.join('\n')}

SSIM is the mean page-penalized grayscale score at 150 DPI, without resizing or alignment correction. Missing or extra pages are penalized. DOCX uses the pinned CDN fonts. **— = not measured.** One demo does not establish corpus-wide quality or a leaderboard rank.

The commit column pins the tested source revision; generated README-only commits are excluded. Office versions, UTC render times, source files, page PNGs, and hashes are recorded per sample: ${sources.join(', ') || 'no reference samples yet'}.
${END}`;
}

export function updateReadme(readme, section) {
  if (!section.startsWith(BEGIN) || !section.endsWith(END))
    throw new Error('Invalid generated section');
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (begin < 0 !== end < 0 || (begin >= 0 && end < begin))
    throw new Error('Broken generated markers');
  const stripped =
    begin >= 0
      ? readme.slice(0, begin) + readme.slice(end + END.length)
      : readme.replace(/^## Visual fidelity\n[\s\S]*?(?=^## |$(?![\s\S]))/m, '');
  const position = stripped.indexOf('## Contributing\n');
  if (position < 0) throw new Error('README has no Contributing section');
  return `${stripped.slice(0, position).trimEnd()}\n\n${section}\n\n${stripped.slice(position)}`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const [reportPath, readmePath = 'README.md'] = process.argv.slice(2);
  if (!reportPath) throw new Error('usage: readme.mjs report.json [README.md]');
  const section = renderSection(JSON.parse(await readFile(reportPath, 'utf8')));
  await writeFile(readmePath, updateReadme(await readFile(readmePath, 'utf8'), section));
}
