import os
from typing import Any, Mapping, final

__version__: str
MAX_PIXMAP_DIM: int
MAX_PIXMAP_PIXELS: int

class DocxError(Exception): ...
class ParseError(DocxError): ...
class EditError(DocxError): ...
class UnsupportedEditError(EditError): ...
class LayoutError(DocxError): ...
class RenderError(DocxError): ...

@final
class TextRun:
    @property
    def text(self) -> str: ...
    @property
    def bold(self) -> bool | None: ...
    @property
    def italic(self) -> bool | None: ...
    @property
    def underline(self) -> str | None: ...
    @property
    def strike(self) -> bool | None: ...
    @property
    def font_size(self) -> float | None:
        """Points, converted from the half-points `w:sz` carries."""
    @property
    def font_family(self) -> str | None: ...
    @property
    def color(self) -> str | None:
        """Explicit RGB. A theme colour reads as `None`."""
    @property
    def style_id(self) -> str | None: ...

@final
class Paragraph:
    @property
    def id(self) -> str | None: ...
    @property
    def style(self) -> str | None: ...
    @property
    def alignment(self) -> str | None: ...
    @property
    def runs(self) -> list[TextRun]: ...
    @property
    def text(self) -> str: ...

@final
class TableCell:
    @property
    def paragraphs(self) -> list[Paragraph]: ...
    @property
    def tables(self) -> list[Table]: ...
    @property
    def text(self) -> str: ...

@final
class TableRow:
    @property
    def cells(self) -> list[TableCell]: ...
    @property
    def text(self) -> str: ...
    def __len__(self) -> int: ...

@final
class Table:
    @property
    def rows(self) -> list[TableRow]: ...
    @property
    def column_widths(self) -> list[float] | None: ...
    @property
    def text(self) -> str: ...
    def __len__(self) -> int: ...

@final
class Section:
    @property
    def id(self) -> str | None: ...
    @property
    def page_width(self) -> float | None: ...
    @property
    def page_height(self) -> float | None: ...
    @property
    def orientation(self) -> str | None: ...
    @property
    def margin_top(self) -> float | None: ...
    @property
    def margin_bottom(self) -> float | None: ...
    @property
    def margin_left(self) -> float | None: ...
    @property
    def margin_right(self) -> float | None: ...
    @property
    def paragraphs(self) -> list[Paragraph]: ...
    @property
    def text(self) -> str: ...

@final
class HeaderFooter:
    @property
    def rel_id(self) -> str: ...
    @property
    def kind(self) -> str:
        """One of default, first, or even."""
    @property
    def paragraphs(self) -> list[Paragraph]: ...
    @property
    def text(self) -> str: ...

@final
class Structure:
    @property
    def body_paragraphs(self) -> int: ...
    @property
    def body_tables(self) -> int: ...
    @property
    def sections(self) -> int: ...
    @property
    def headers(self) -> int: ...
    @property
    def footers(self) -> int: ...
    @property
    def footnotes(self) -> int: ...
    @property
    def endnotes(self) -> int: ...

@final
class Edit:
    @property
    def para_id(self) -> str | None: ...
    @property
    def story(self) -> str | None: ...
    @property
    def start(self) -> int | None: ...
    @property
    def end(self) -> int | None: ...
    @property
    def new_para_ids(self) -> list[str]: ...
    @property
    def revision_ids(self) -> list[str]: ...

@final
class DisplayList:
    @staticmethod
    def from_json(text: str) -> DisplayList: ...
    @property
    def contract_version(self) -> int | None: ...
    @property
    def json(self) -> str: ...
    @property
    def primitives(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def write(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int:
        """Page count."""

@final
class Layout:
    @property
    def pages(self) -> int: ...
    @property
    def display_list(self) -> DisplayList: ...
    @property
    def json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def write(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int: ...

@final
class Png:
    @property
    def bytes(self) -> bytes: ...
    @property
    def skipped_images(self) -> int: ...
    def write(self, path: str | os.PathLike[str]) -> None: ...
    def __len__(self) -> int: ...

@final
class Document:
    @staticmethod
    def open(data: bytes, *, limits: dict[str, int] | None = ...) -> Document: ...
    @staticmethod
    def open_path(
        path: str | os.PathLike[str], *, limits: dict[str, int] | None = ...
    ) -> Document: ...
    author: str
    origin: str
    timestamp: str
    @property
    def paragraph_ids(self) -> list[str | None]: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def template_variables(self) -> list[str]: ...
    @property
    def text(self) -> str: ...
    def structure(self) -> Structure: ...
    def paragraphs(self) -> list[Paragraph]: ...
    def tables(self) -> list[Table]: ...
    def sections(self) -> list[Section]: ...
    def headers(self) -> list[HeaderFooter]: ...
    def footers(self) -> list[HeaderFooter]: ...
    def paragraph(self, paragraph: int | str) -> Paragraph: ...
    def replace_text(self, para_id: str, text: str) -> Edit: ...
    def layout(self, input: str | Mapping[str, Any]) -> Layout: ...
    def register_font(
        self, family: str, data: bytes, *, bold: bool = ..., italic: bool = ...
    ) -> int: ...
    def register_image(
        self, rel_id: str, data: bytes, *, scope: str = ..., part: str | None = ...
    ) -> None: ...
    def render_png(self, display_list: DisplayList, page: int = ...) -> Png: ...
    def save(
        self,
        *,
        now: str | None = ...,
        update_modified_date: bool = ...,
        modified_by: str | None = ...,
    ) -> bytes: ...
    def save_path(
        self,
        path: str | os.PathLike[str],
        *,
        now: str | None = ...,
        update_modified_date: bool = ...,
        modified_by: str | None = ...,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, paragraph: int | str) -> Paragraph: ...
